steps:
  # Build the container image with a SAFE name
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-t', 'gcr.io/$PROJECT_ID/pulse-feeds-app:latest', '.']

  # Push the container image to Container Registry
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'gcr.io/$PROJECT_ID/pulse-feeds-app:latest']

  # Deploy container image to Cloud Run
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: gcloud
    args:
    - 'run'
    - 'deploy'
    - 'pulse-feeds'
    - '--image'
    - 'gcr.io/$PROJECT_ID/pulse-feeds-app:latest'
    - '--region'
    - 'europe-west2'
    - '--platform'
    - 'managed'
    - '--allow-unauthenticated'

images:
  - 'gcr.io/$PROJECT_ID/pulse-feeds-app:latest'

timeout: '1200s'
options:
  logging: CLOUD_LOGGING_ONLY
