steps:
  # Build the container image
  - name: 'gcr.io/cloud-builders/docker'
    args: [
      'build', 
      '-t', 'gcr.io/consumer-rewards-app-2026/pulse-feeds-final', 
      '--build-arg', 'VITE_GOOGLE_MAPS_API_KEY=${_VITE_GOOGLE_MAPS_API_KEY}',
      '--build-arg', 'VITE_GOOGLE_MAPS_MAP_ID=${_VITE_GOOGLE_MAPS_MAP_ID}',
      '.'
    ]

  # Push the container image
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'gcr.io/consumer-rewards-app-2026/pulse-feeds-final']

  # Deploy to Cloud Run
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: gcloud
    args:
      [
        'run',
        'deploy',
        'pulse-feeds',
        '--image',
        'gcr.io/consumer-rewards-app-2026/pulse-feeds-final',
        '--region',
        'europe-west2',
        '--platform',
        'managed',
        '--allow-unauthenticated'
      ]

images:
  - 'gcr.io/consumer-rewards-app-2026/pulse-feeds-final'

timeout: '1200s'
options:
  logging: CLOUD_LOGGING_ONLY
