steps:
  # Build the container image
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-t', 'gcr.io/consumer-rewards-app-2026/pulse-feeds-prod', '.']

  # Push the container image
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'gcr.io/consumer-rewards-app-2026/pulse-feeds-prod']

  # Deploy to Cloud Run
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: gcloud
    args:
      [
        'run',
        'deploy',
        'pulse-feeds',
        '--image',
        'gcr.io/consumer-rewards-app-2026/pulse-feeds-prod',
        '--region',
        'europe-west2',
        '--platform',
        'managed',
        '--allow-unauthenticated'
      ]

images:
  - 'gcr.io/consumer-rewards-app-2026/pulse-feeds-prod'

timeout: '1200s'
options:
  logging: CLOUD_LOGGING_ONLY
